scrape_configs:
  - job_name: 'websys'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'websys'

  - job_name: 'prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'prometheus:9090' ]
        labels:
          application: 'prometheus'